---
- name: Update and Upgrade Ubuntu Packages
  hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: yes
