---
- name: Update and Upgrade Ubuntu Packages
  hosts: all
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: yes

    - name: Remove packages that are no longer required
      ansible.builtin.apt:
        autoremove: true

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Report reboot required
      ansible.builtin.debug:
        msg: "REBOOT REQUIRED on {{ inventory_hostname }}"
      when: reboot_required.stat.exists

    - name: Report no reboot required
      ansible.builtin.debug:
        msg: "No reboot required on {{ inventory_hostname }}"
      when: not reboot_required.stat.exists
