---
- name: Install Ansible on Ubuntu Hosts
  hosts: all
  become: yes  # Use sudo to install packages
  tasks:
    - name: Update the apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Ansible
      ansible.builtin.apt:
        name: ansible
        state: present

    - name: Verify Ansible installation
      ansible.builtin.command: ansible --version
      register: ansible_version

    - name: Print Ansible version
      ansible.builtin.debug:
        msg: "Ansible installed successfully: {{ ansible_version.stdout }}"
