---
- name: Force rebalance of Docker Swarm
  hosts: all
  become: yes
  tasks:
    - name: Get the list of Docker Swarm nodes
      ansible.builtin.shell: docker node ls --format '{{"{{.ID}}"}}'
      register: docker_nodes
      changed_when: false  # This task is only for gathering information

    - name: Drain all nodes except the manager
      ansible.builtin.shell: docker node update --availability drain {{ item }}
      loop: "{{ docker_nodes.stdout_lines }}"
      when: item != (ansible_hostname | lower)  # Skip manager node

    - name: Sleep for a few seconds to allow tasks to migrate
      ansible.builtin.pause:
        seconds: 10

    - name: Bring all nodes back online
      ansible.builtin.shell: docker node update --availability active {{ item }}
      loop: "{{ docker_nodes.stdout_lines }}"
