---
- name: Force rebalance of Docker Swarm (without manager running tasks)
  hosts: all
  become: yes
  tasks:
    - name: Get the list of Docker Swarm nodes and their roles
      ansible.builtin.shell: docker node ls --format '{{json .}}'
      register: docker_nodes
      changed_when: false

    - name: Parse node details and drain worker nodes
      ansible.builtin.shell: docker node update --availability drain {{ item.ID }}
      loop: "{{ docker_nodes.stdout_lines | map('from_json') | list }}"
      when: item.Role == 'worker'

    - name: Set manager node to drain (to avoid scheduling tasks on it)
      ansible.builtin.shell: docker node update --availability drain {{ item.ID }}
      loop: "{{ docker_nodes.stdout_lines | map('from_json') | list }}"
      when: item.Role == 'manager'

    - name: Sleep for a few seconds to allow tasks to migrate
      ansible.builtin.pause:
        seconds: 10

    - name: Bring all worker nodes back online
      ansible.builtin.shell: docker node update --availability active {{ item.ID }}
      loop: "{{ docker_nodes.stdout_lines | map('from_json') | list }}"
      when: item.Role == 'worker'
