---
- name: Force rebalance of Docker Swarm services
  hosts: all
  become: yes
  tasks:
    - name: Get the list of Docker Swarm nodes and their roles
      ansible.builtin.shell: docker node ls --format '{{"{{.ID}}"}} {{ "{{.Hostname}}" }} {{ "{{.Role}}" }} {{ "{{.Availability}}" }}'
      register: docker_nodes
      changed_when: false

    - name: Debug node information (optional)
      debug:
        var: docker_nodes.stdout_lines

    - name: Drain all worker nodes to force service migration
      ansible.builtin.shell: docker node update --availability drain {{ item.split()[0] }}
      loop: "{{ docker_nodes.stdout_lines }}"
      when: "'worker' in item"

    - name: Set manager node to 'drain' to prevent scheduling of services unless needed
      ansible.builtin.shell: docker node update --availability drain {{ item.split()[0] }}
      loop: "{{ docker_nodes.stdout_lines }}"
      when: "'manager' in item"

    - name: Sleep for a few seconds to allow service migration
      ansible.builtin.pause:
        seconds: 15

    - name: Bring all worker nodes back online to rebalance services
      ansible.builtin.shell: docker node update --availability active {{ item.split()[0] }}
      loop: "{{ docker_nodes.stdout_lines }}"
      when: "'worker' in item"

    - name: Set manager node to 'active' but only allow scheduling if worker nodes fail
      ansible.builtin.shell: docker node update --availability active {{ item.split()[0] }}
      loop: "{{ docker_nodes.stdout_lines }}"
      when: "'manager' in item"
