---
- name: Docker System Prune on Swarm Host
  hosts: docker_swarm_host  # Replace this with your inventory group or host
  become: yes               # Ensures the playbook is run with elevated privileges
  tasks:
    - name: Run Docker System Prune
      ansible.builtin.command:
        cmd: docker system prune -f
      register: prune_result

    - name: Display Prune Results
      debug:
        var: prune_result.stdout

